\
                /* This file was generated by blade */
                extern "C" {
                namespace binary_version {
                extern const int kSvnInfoCount = 1;
                extern const char* const kSvnInfo[] = {"unknown@unknown\n"};
                extern const int kScmInfoCount = 1;
                extern const char* const kScmInfo[] = {"unknown@unknown\n"};
                extern const char kBuildType[] = "release";
                extern const char kBuildTime[] = "Thu Nov 16 14:00:45 2023";
                extern const char kBuilderName[] = "zifeng";
                extern const char kHostName[] = "cat";
                extern const char kCompiler[] = "gcc 11";
                }}