language: c++
os: linux
sudo: false

matrix:
  include:

    - env: CLANG_VERSION=3.5
      addons: &clang35
        apt:
          packages:
            - clang-3.5
            - llvm-3.5
            - llvm-3.5-tools
            - llvm-toolchain-3.5
            - valgrind
            - libboost-all-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

    - env: CLANG_VERSION=3.6
      addons: &clang36
        apt:
          packages:
            - clang-3.6
            - llvm-3.6
            - llvm-3.6-tools
            - llvm-toolchain-3.6
            - valgrind
            - libboost-all-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - env: GCC_VERSION=4.8
      addons: &gcc48
        apt:
          packages:
            - gcc-4.8
            - g++-4.8
            - valgrind
            - libboost-all-dev
          sources:
            - ubuntu-toolchain-r-test

    - env: GCC_VERSION=4.9
      addons: &gcc49
        apt:
          packages:
            - gcc-4.9
            - g++-4.9
            - valgrind
            - libboost-all-dev
          sources:
            - ubuntu-toolchain-r-test

    - env: GCC_VERSION=5
      addons: &gcc49
        apt:
          packages:
            - gcc-5
            - g++-5
            - valgrind
            - libboost-all-dev
          sources:
            - ubuntu-toolchain-r-test

install:
  - cd ${TRAVIS_BUILD_DIR} && tools/deps
script:
  - cd ${TRAVIS_BUILD_DIR} && tools/test
after_success:
  - cd ${TRAVIS_BUILD_DIR} && tools/coverage
